 # Defines all the containers (services) that will run
services:
#  app:
#    image: my-gym-app-image:latest  # Replace with your actual image name
#    container_name: gym-app-container
#    restart: always
#    depends_on:
#      - db
#    env_file:
#      - .env
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#    ports:
#      - "8080:8080"
#    networks:
#      - my-network

  db:
    container_name: postgres-db-gym-app-container
    image: postgres:17  # Use the appropriate PostgreSQL version
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: gym_app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234567a
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase
    volumes:
      - ./src/main/resources/liquibase/changelog:/liquibase/changelog
#    environment:
#      - LIQUIBASE_URL=jdbc:postgresql://db:5432/gym_app_db
#      - LIQUIBASE_USERNAME=root
#      - LIQUIBASE_PASSWORD=1234567a
#      - LIQUIBASE_CHANGELOG_FILE=/liquibase/changelog/db.changelog-master.xml
    depends_on:
      - db
    entrypoint: ["update"]

volumes:
  postgres_data:
