spring:
  application:
    name: gym_app

  datasource:
    url: jdbc:postgresql://localhost:5432/gym-app-db
    username: root
    password: 1234567a
    driver-class-name: org.postgresql.Driver
#
#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.xml
